"""Privacy-preserving, immutable records for serving requests.

The serving API never stores request bodies, screenshots, prompts, targets, or provider response
text here.  It stores only the operational fields needed to reconstruct which approved policy
handled a request and how that request ended.
"""

from __future__ import annotations

import json
import math
import re
import threading
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from typing import Any, Protocol

from pixelgym.platform.fingerprints import canonical_json_bytes
from pixelgym.platform.immutable_store import ImmutableStore

OPERATIONAL_RECORD_SCHEMA_VERSION = "pixelgym-serving-operational-record-v1"
_REQUEST_ID = re.compile(r"^srv-[0-9a-f]{32}$")
_PROVIDER_REQUEST_ID = re.compile(r"^[A-Za-z0-9._:-]{1,256}$")
_USAGE_KEY = re.compile(r"^[a-z][a-z0-9_]{0,63}$")


class OperationalLogError(RuntimeError):
    """A serving record could not be written or verified."""


@dataclass(frozen=True)
class OperationalRecord:
    """A stable, redacted record of one request to the grounding endpoint."""

    schema_version: str
    request_id: str
    occurred_at: str
    policy_id: str | None
    deployment_id: str | None
    exact_policy_version: str | None
    terminal_status: str
    http_status: int
    latency_ms: float
    provider_latency_ms: float | None
    provider_request_id: str | None
    usage: dict[str, int | float] | None

    def __post_init__(self) -> None:
        if self.schema_version != OPERATIONAL_RECORD_SCHEMA_VERSION:
            raise ValueError("unsupported operational record schema")
        if not _REQUEST_ID.fullmatch(self.request_id):
            raise ValueError("operational request ID is malformed")
        try:
            occurred_at = datetime.fromisoformat(self.occurred_at)
        except (TypeError, ValueError) as exc:
            raise ValueError("operational timestamp is malformed") from exc
        if occurred_at.tzinfo is None or occurred_at.utcoffset() != UTC.utcoffset(occurred_at):
            raise ValueError("operational timestamp must be UTC")
        if not self.terminal_status or not 100 <= self.http_status <= 599:
            raise ValueError("operational terminal status and HTTP status are required")
        if not math.isfinite(self.latency_ms) or self.latency_ms < 0:
            raise ValueError("operational latency must be finite and nonnegative")
        if self.provider_latency_ms is not None and (
            not math.isfinite(self.provider_latency_ms) or self.provider_latency_ms < 0
        ):
            raise ValueError("provider latency must be finite and nonnegative")
        if self.provider_request_id is not None and not _PROVIDER_REQUEST_ID.fullmatch(
            self.provider_request_id
        ):
            raise ValueError("provider request ID is malformed")
        if self.usage is not None:
            for key, value in self.usage.items():
                if (
                    not _USAGE_KEY.fullmatch(key)
                    or isinstance(value, bool)
                    or not isinstance(value, (int, float))
                    or not math.isfinite(value)
                    or value < 0
                ):
                    raise ValueError("operational usage is malformed")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class OperationalLog(Protocol):
    def append(self, record: OperationalRecord) -> None: ...

    def get(self, request_id: str) -> OperationalRecord | None: ...


class ImmutableOperationalLog:
    """Append-only operational records backed by the configured immutable store.

    Record IDs are collision-resistant random UUID material generated by the service.  The
    deterministic logical key makes a record independently retrievable and each read rechecks the
    immutable store's pinned digest/version boundary.
    """

    def __init__(self, store: ImmutableStore) -> None:
        self.store = store
        self._lock = threading.RLock()

    @staticmethod
    def _key(request_id: str) -> str:
        if not _REQUEST_ID.fullmatch(request_id):
            raise ValueError("operational request ID is malformed")
        return f"serving-operational-records/{request_id}.json"

    def append(self, record: OperationalRecord) -> None:
        key = self._key(record.request_id)
        data = canonical_json_bytes(record.to_dict()) + b"\n"
        with self._lock:
            try:
                reference = self.store.put_once(key, data, media_type="application/json")
                if self.store.get_verified(reference) != data:
                    raise OperationalLogError("operational record verification returned changed bytes")
            except Exception as exc:
                raise OperationalLogError("failed to durably record serving operation") from exc

    def get(self, request_id: str) -> OperationalRecord | None:
        key = self._key(request_id)
        with self._lock:
            try:
                reference = self.store.get_reference(key)
                if reference is None:
                    return None
                value = json.loads(self.store.get_verified(reference))
                record = OperationalRecord(**value)
            except OperationalLogError:
                raise
            except Exception as exc:
                raise OperationalLogError("failed to retrieve verified serving operation") from exc
        if record.request_id != request_id:
            raise OperationalLogError("operational record identity does not match its key")
        return record


class MemoryOperationalLog:
    """Explicit test/smoke-only log; traffic serving must use ImmutableOperationalLog."""

    def __init__(self) -> None:
        self._records: dict[str, OperationalRecord] = {}
        self._lock = threading.RLock()

    def append(self, record: OperationalRecord) -> None:
        with self._lock:
            if record.request_id in self._records:
                raise OperationalLogError("duplicate operational request ID")
            self._records[record.request_id] = record

    def get(self, request_id: str) -> OperationalRecord | None:
        with self._lock:
            return self._records.get(request_id)
